// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fhrLxbKwohyxJWsXxhY_uwaaAZbSZiY',
    appId: '1:346023063846:android:13dbbae264d4abe2d091e7',
    messagingSenderId: '346023063846',
    projectId: 'myfirstfone-df8af',
    storageBucket: 'myfirstfone-df8af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIST2yUZNu5eGUS3ASPd3H93sCaHavdQ',
    appId: '1:346023063846:ios:5ef0dc829a15d0e0d091e7',
    messagingSenderId: '346023063846',
    projectId: 'myfirstfone-df8af',
    storageBucket: 'myfirstfone-df8af.appspot.com',
    androidClientId: '346023063846-bqiau440u7a3a5q328fvrp3u6k0octeo.apps.googleusercontent.com',
    iosClientId: '346023063846-i1qshrge5ia10qqia3f8kccg6vv93thd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapExam',
  );
}
